### ISSUE TITLE
Kali Linux Version

### ISSUE THREAD

**Issue by Max0nyM** [arnaucode/coffeeMiner#1]
Hi Which version of kali linux 2 ur using? Cuz i cant run mitmdump in Kali Linux 2 2017.3
There is some error with bs4 module.

**Comment by Thenatdead** [comment]
Same for me

**Comment by arnaucube** [comment]
I downloaded the mitmproxy ( [https://mitmproxy.org/](https://mitmproxy.org/) ) directly from pip.
The complete installation steps are in the 'installer.sh' file: [https://github.com/arnaucode/coffeeMiner/blob/master/install.sh](https://github.com/arnaucode/coffeeMiner/blob/master/install.sh)
