### ISSUE TITLE
Use ethernet

### ISSUE THREAD

**Issue by PigiBouxx** [arnaucode/coffeeMiner#11]
Hi,
I have a raspberry pi3, imagine we plug it to ethernet, can we inject js, into web page?

**Comment by arnaucube** [comment]
yes, it would be possible

**Comment by PigiBouxx** [comment]
How?

**Comment by arnaucube** [comment]
like running it in a Linux laptop
here you can found some examples: [http://lmgtfy.com/?q=raspberrypi+ethernet+mitm](http://lmgtfy.com/?q=raspberrypi+ethernet+mitm)

**Comment by PigiBouxx** [comment]
Oki, thx for the animation ^^, i will more search
