### ISSUE TITLE
how to implement on mac?

### ISSUE THREAD

**Issue by parkminhyung** [arnaucode/coffeeMiner#19]
i do not know how to implement progress of "echo 1 > .... "  on terminal of mac. 
i thought this progress is one of hacking wifi. but this is for linux, not for mac. so, it did not work on mac. if implement coffeeMiner.py, terminal showed the error message: /proc/sys/net/ipv4/ip_forward: No such file or directory

others were worked.

**Comment by arnaucube** [comment]
Sorry, I don't know. I use Linux.
The concept behind, is to enable the ip forwarding, maybe you can search something arround this.
Another option could be to run a Linux virtual machine inside the Mac.
Hope that this answer helps.

**Comment by parkminhyung** [comment]
thanks for your answer. i will try

**Comment by dotaxis** [comment]
Check out this link: https://salferrarello.com/mac-pfctl-port-forwarding/

IP forwarding in OSX is pretty weird but it's not impossible to achieve what we need AFAIK.
