### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by S0rryMyBad** [arnaucode/coffeeMiner#2]
OS: BackBox v5

![screenshot_2018-01-08_03-52-06](https://user-images.githubusercontent.com/24543191/34653982-9a2d5010-f427-11e7-90ad-c5bc03d0759a.png)

**Comment by arnaucube** [comment]
This syntax error, is due the version of python being used. As appears in the image, it seems to be running with python 2.7, the CoffeeMiner is build with python 3 syntax and libraries.
