### ISSUE TITLE
Possible on Termux?

### ISSUE THREAD

**Issue by mpamop** [arnaucode/coffeeMiner#31]
Is it possible to bet on termux? And how?

**Comment by MisterBianco** [comment]
To bet? Doubt it gambling on termux might be hard.

However the terminal emulator doesn't matter when running coffeeminer

**Comment by mpamop** [comment]
Give a normal translator...
Is it possible to run this miner on termux?

**Comment by MisterBianco** [comment]
Yes, it will run on any terminal emulator.
